---
# tasks file for docker
- name: get docker install script
  get_url:
      url: '{{ script_url }}'
      dest: '{{ script_path }}'
- name: run script
  become: yes
  command: 'sh {{ script_path }}' 
- name: remove script
  file:
      path: '{{ script_path }}' 
      state: absent
      
- name: create docker group
  become: yes
  group:
      name: docker
      state: present
- name: add ssh user to group
  become: yes
  user:
      name: "{{ item }}"
      groups: docker
      append: yes
  with_items: "{{ ansible_user_array }}"
  when: ansible_user_array
      
  
